use Practic
Go
--Solution: SET TRANSACTION ISOLATION LEVEL TO READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
select * from Customers
WAITFOR DELAY '00:00:15'
select * from Customers
COMMIT TRAN