use MiniFacebook_IE
Go
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Categories
WAITFOR DELAY '00:00:05'
SELECT * FROM Categories
COMMIT TRAN



use MiniFacebook_IE
Go
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Categories
WAITFOR DELAY '00:00:05'
SELECT * FROM Categories
COMMIT TRAN